### PR TITLE
Patch unset attributes with `MISSING` during model serialization with `exclude_unset`

### LINKED ISSUE #12888: model_dump(exclude_unset=True) produces spurious warnings for Union members with unset defaults
## Description

`model_dump(exclude_unset=True)` on a model containing a `Union` field produces spurious `PydanticSerializationUnexpectedValue` warnings when a union member has unset fields with defaults.

## Reproduction

```python
from typing import Literal

from pydantic import BaseModel


class Cat(BaseModel):
    type: Literal['cat']
    color: str | None = None  # field with default


class Dog(BaseModel):
    type: Literal['dog']


class Zoo(BaseModel):
    animals: list[Cat | Dog]


cat = Cat(type='cat')
zoo = Zoo(animals=[cat])

# Sanity check: model_dump without exclude_unset works fine
assert zoo.model_dump() == {'animals': [{'type': 'cat', 'color': None}]}

# Sanity check: model_dump(exclude_unset=True) on the Cat alone works fine
assert cat.model_dump(exclude_unset=True) == {'type': 'cat'}

# BUG: model_dump(exclude_unset=True) on the parent Zoo produces warnings
assert zoo.model_dump(exclude_unset=True) == {'animals': [{'type': 'cat'}]}
```

The last line produces:

```
UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 2 fields but got 1: Expected `Cat` - serialized value may not be as expected [field_name='animals', ...])
  PydanticSerializationUnexpectedValue(Expected `Dog` - serialized value may not be as expected [field_name='animals', ...])
```

The output is correct, but the warnings are spurious.

## Version info

- **Broken**: pydantic 2.13.0b2 / pydantic-core 2.42.0 (installed from latest on github)
- **Works**: pydantic 2.12.5 / pydantic-core 2.41.5
- Python 3.12

### PR DESCRIPTION
**Pull request by davidhewitt**
## Change Summary

This is a possible fix for #12888 that avoids regressing the tests previously added.

The approach is to use the missing sentinel to signal which fields are unset during serialization instead of removing them from the dictionary.

Note: I think this is probably user-observable with custom serializer functions (e.g. wrap serializers); I'm unsure if that means that this approach is not ok (or has to be limited only to when there are no model serializers present). We should discuss.

## Related issue number

Fixes #12888 

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

### CODE REVIEW

**Comment by Viicos** [comment]
> Note: I think this is probably user-observable with custom serializer functions (e.g. wrap serializers); I'm unsure if that means that this approach is not ok (or has to be limited only to when there are no model serializers present). We should discuss.

It looks like the following behaves as expected?

```python
from typing import Annotated

from pydantic import BaseModel, WrapSerializer, model_serializer


def ser(v, h):
    # not called
    return h(v)


class Model(BaseModel):
    a: Annotated[int, WrapSerializer(ser)] = 1

    @model_serializer(mode='wrap')
    def ser_model(self, handler):
        rv = handler(self)
        print(rv)  # {}
        return rv

m = Model()
m.model_dump(exclude_unset=True)
```

File: pydantic-core/src/serializers/type_serializers/model.rs [hunk 1]
```diff
@@ -217,18 +218,29 @@ impl ModelSerializer {
         let py: Python<'_> = model.py();
         let mut attrs = model.getattr(intern!(py, "__dict__"))?.cast_into::<PyDict>()?;
 
+        // If excluding unset fields, mask any fields not in `__pydantic_fields_set__` with the
+        // missing sentinel so that the fields serializer will exclude them from the output.
```
Comment (Viicos) [inline pydantic-core/src/serializers/type_serializers/model.rs:222]:
```suggestion
        // If excluding unset fields, mask any fields not in `__pydantic_fields_set__` with the
        // missing sentinel so that the fields serializer will exclude them from the output.
        // The `GeneralFieldsSerializer` makes sure to exclude the value, so any user-defined
        // serializer won't be called.
```

**Review by Viicos — APPROVED** [review]
